### ISSUE TITLE
Make the "chain" name match any character

### ISSUE THREAD

**Issue by phanirajgoutham** [wkronmiller/iptables-parser#1]
Hi @wkronmiller ,

Thanks for doing this. I found it very helpful.

In my case the custom chain, are in smaller case, and few of them are also hypenated. 
Would be very helpful, if you could facilitate that.

Thanks,
Phani

**Comment by wkronmiller** [comment]
Hey @phanirajgoutham,

Nice catch! I just released a fix, which should be available starting from ```0.0.33```. 

Feel free to open more issues if you find any other problems.

Best,
Rory
